/**
 * Assemble a clean, symlink-free deploy directory (`site/`) after `tsc`.
 *
 * Cloudflare Pages refuses an output directory containing symlinks it can't
 * resolve ("build output directory contains links to files that can't be
 * accessed") — and a pnpm workspace's `node_modules` is full of them. Pointing
 * Pages at `apps/dashboard` (which has `node_modules` next to `dist/`) hits
 * that every time. So `site/` holds only real files, copied, never symlinked.
 *
 * There is ONE Pages project, and this directory is everything it publishes.
 * So it holds the whole public surface, not just the dashboard:
 *
 *   /        landing page      <- apps/web/index.html
 *   /docs    public docs       <- apps/web/docs (generated by build-docs.mjs)
 *   /app     the product       <- this package
 *
 * The landing page and docs must be at the root: they are what a visitor and a
 * crawler should find at the domain. A login screen at the front door hides
 * everything the product has to say for itself. The dashboard moves under
 * /app, which it can do because it is HASH-routed (see src/shell.ts —
 * `location.hash`), so every in-app route is /app/#/pulse and no server-side
 * SPA fallback is involved. Its asset paths are relative ("./styles.css",
 * "./dist/app.js"), so they resolve under /app without rewriting.
 *
 * apps/web is not a separate deploy — it is build input for this directory.
 */
import { cpSync, readFileSync, writeFileSync, rmSync, mkdirSync, readdirSync, statSync, lstatSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const site = join(root, 'site');
const web = join(root, '..', 'web');

rmSync(site, { recursive: true, force: true });
mkdirSync(site, { recursive: true });

/* ——— The product, at /app ————————————————————————————————————— */
const app = join(site, 'app');
mkdirSync(app, { recursive: true });
cpSync(join(root, 'dist'), join(app, 'dist'), { recursive: true, dereference: true });
cpSync(join(root, 'styles.css'), join(app, 'styles.css'), { dereference: true });
writeFileSync(join(app, 'index.html'), appHtml());

/**
 * The product's index.html, with the API origin written into it.
 *
 * The dashboard and apps/api are two deployments on two origins, and since
 * sign-in goes through the API (`POST /auth/login`) the page cannot do anything
 * at all — not even show a signed-in user — until it knows that origin. Asking
 * the person signing in is the wrong place to solve it: they are three
 * teammates, not operators, and the answer is the same for all of them and
 * fixed at deploy time. So the build answers it.
 *
 * Unset is legitimate — a local build reaches `wrangler dev` on
 * localhost:8787 without any of this (see `getApiBaseUrl` in src/api.ts) — so
 * this warns rather than failing. It warns loudly, because an unset value on a
 * *deployed* build is a site nobody can sign in to, and the build log is the
 * only place that fact appears.
 */
function appHtml() {
  let html = readFileSync(join(root, 'index.html'), 'utf8');
  html = withLogoToken(html);
  const base = (process.env.ENGINE_API_BASE ?? '').trim().replace(/\/$/, '');
  if (!base) {
    console.warn(
      'assembleSite: ENGINE_API_BASE is not set. Fine for a local build (the app falls back to\n' +
        '              http://localhost:8787), but a DEPLOYED build without it cannot reach the API,\n' +
        '              and sign-in goes through the API — so nobody will be able to log in.',
    );
    return html;
  }
  // JSON.stringify, not quotes: it escapes anything that would otherwise break
  // out of the string literal or close the script tag early.
  const tag = `  <script>window.ENGINE_API_BASE=${JSON.stringify(base).replace(/</g, '\\u003c')};</script>\n`;
  if (!html.includes('<body>')) {
    console.error('assembleSite: index.html has no <body> to inject ENGINE_API_BASE before.');
    process.exit(1);
  }
  console.log(`assembleSite: ENGINE_API_BASE = ${base}`);
  return html.replace('<body>', `<body>\n${tag}`);
}

/**
 * Optional override for the logo.dev publishable key.
 *
 * Unlike ENGINE_API_BASE this warns about nothing when unset, because
 * src/logo.ts ships a working default — the key is publishable, so a build
 * with no configuration still renders logos. Set ENGINE_LOGO_TOKEN only to
 * bill logo requests to a different logo.dev account.
 */
function withLogoToken(html) {
  const value = (process.env.ENGINE_LOGO_TOKEN ?? '').trim();
  if (!value) return html;
  if (!html.includes('<body>')) {
    console.error('assembleSite: index.html has no <body> to inject ENGINE_LOGO_TOKEN before.');
    process.exit(1);
  }
  const tag = `  <script>window.ENGINE_LOGO_TOKEN=${JSON.stringify(value).replace(/</g, '\\u003c')};</script>\n`;
  console.log('assembleSite: ENGINE_LOGO_TOKEN set (overriding the built-in publishable key)');
  return html.replace('<body>', `<body>\n${tag}`);
}

/* ——— Landing page at /, public docs at /docs —————————————————————
   build-docs.mjs regenerates apps/web/docs from apps/web/content and its own
   authored copy; it resolves every path from its own location, so cwd here is
   irrelevant. stdio:'inherit' means its BANNED-term check fails this build
   loudly rather than shipping a half-built docs tree. */
execFileSync(process.execPath, [join(web, 'build-docs.mjs')], { stdio: 'inherit' });
cpSync(join(web, 'index.html'), join(site, 'index.html'), { dereference: true });
cpSync(join(web, 'docs'), join(site, 'docs'), { recursive: true, dereference: true });

/* Verify what this script promises: no symlink survived (Pages rejects the
   whole deploy for one), and every route the docs nav links to is really a
   file. A silent miss here is a blank page in production. */
const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (lstatSync(p).isSymbolicLink()) {
      console.error(`assembleSite: symlink survived at ${relative(site, p)} — Pages will reject this.`);
      process.exit(1);
    }
    if (statSync(p).isDirectory()) walk(p);
    else files.push(relative(site, p));
  }
})(site);

const required = [
  'index.html',
  'app/index.html',
  'app/styles.css',
  'app/dist/app.js',
  'docs/index.html',
  'docs/docs.css',
  'docs/changelog/index.html',
  'docs/features/index.html',
  'docs/roadmap/index.html',
];
const missing = required.filter((f) => !files.includes(f));
if (missing.length) {
  console.error('assembleSite: expected routes missing from the output:\n  ' + missing.join('\n  '));
  process.exit(1);
}

/* The root must be the landing page, not the app shell. Getting this backwards
   is the bug this whole layout exists to fix, and it is invisible in a build
   log — both files are called index.html and both are valid HTML. */
const rootHtml = readFileSync(join(site, 'index.html'), 'utf8');
if (/name="robots"[^>]*noindex/.test(rootHtml)) {
  console.error('assembleSite: the root index.html is noindex — that is the dashboard shell, not the landing page.');
  process.exit(1);
}

console.log(`Assembled ${site} — ${files.length} files, no symlinks.`);
