/**
 * Assemble a clean, symlink-free deploy directory (`site/`) after `tsc`.
 *
 * Cloudflare Pages refuses an output directory containing symlinks it can't
 * resolve ("build output directory contains links to files that can't be
 * accessed") — and a pnpm workspace's `node_modules` is full of them. Pointing
 * Pages at `apps/dashboard` (which has `node_modules` next to `dist/`) hits
 * that every time. So `site/` holds only real files, copied, never symlinked.
 *
 * There is ONE Pages project, and this directory is everything it publishes.
 * So it holds the whole public surface, not just the dashboard:
 *
 *   /        landing page      <- apps/web/index.html
 *   /docs    public docs       <- apps/web/docs (generated by build-docs.mjs)
 *   /app     the product       <- this package
 *
 * The landing page and docs must be at the root: they are what a visitor and a
 * crawler should find at the domain. A login screen at the front door hides
 * everything the product has to say for itself. The dashboard moves under
 * /app, which it can do because it is HASH-routed (see src/shell.ts —
 * `location.hash`), so every in-app route is /app/#/pulse and no server-side
 * SPA fallback is involved. Its asset paths are relative ("./styles.css",
 * "./dist/app.js"), so they resolve under /app without rewriting.
 *
 * apps/web is not a separate deploy — it is build input for this directory.
 */
import { cpSync, readFileSync, writeFileSync, rmSync, mkdirSync, readdirSync, statSync, lstatSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const site = join(root, 'site');
const web = join(root, '..', 'web');

rmSync(site, { recursive: true, force: true });
mkdirSync(site, { recursive: true });

/* ——— The product, at /app ————————————————————————————————————— */
const app = join(site, 'app');
mkdirSync(app, { recursive: true });
cpSync(join(root, 'dist'), join(app, 'dist'), { recursive: true, dereference: true });
cpSync(join(root, 'styles.css'), join(app, 'styles.css'), { dereference: true });
writeFileSync(join(app, 'index.html'), readFileSync(join(root, 'index.html'), 'utf8'));

/* ——— Landing page at /, public docs at /docs —————————————————————
   build-docs.mjs regenerates apps/web/docs from apps/web/content and its own
   authored copy; it resolves every path from its own location, so cwd here is
   irrelevant. stdio:'inherit' means its BANNED-term check fails this build
   loudly rather than shipping a half-built docs tree. */
execFileSync(process.execPath, [join(web, 'build-docs.mjs')], { stdio: 'inherit' });
cpSync(join(web, 'index.html'), join(site, 'index.html'), { dereference: true });
cpSync(join(web, 'docs'), join(site, 'docs'), { recursive: true, dereference: true });

/* Verify what this script promises: no symlink survived (Pages rejects the
   whole deploy for one), and every route the docs nav links to is really a
   file. A silent miss here is a blank page in production. */
const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (lstatSync(p).isSymbolicLink()) {
      console.error(`assembleSite: symlink survived at ${relative(site, p)} — Pages will reject this.`);
      process.exit(1);
    }
    if (statSync(p).isDirectory()) walk(p);
    else files.push(relative(site, p));
  }
})(site);

const required = [
  'index.html',
  'app/index.html',
  'app/styles.css',
  'app/dist/app.js',
  'docs/index.html',
  'docs/docs.css',
  'docs/changelog/index.html',
  'docs/features/index.html',
  'docs/roadmap/index.html',
];
const missing = required.filter((f) => !files.includes(f));
if (missing.length) {
  console.error('assembleSite: expected routes missing from the output:\n  ' + missing.join('\n  '));
  process.exit(1);
}

/* The root must be the landing page, not the app shell. Getting this backwards
   is the bug this whole layout exists to fix, and it is invisible in a build
   log — both files are called index.html and both are valid HTML. */
const rootHtml = readFileSync(join(site, 'index.html'), 'utf8');
if (/name="robots"[^>]*noindex/.test(rootHtml)) {
  console.error('assembleSite: the root index.html is noindex — that is the dashboard shell, not the landing page.');
  process.exit(1);
}

console.log(`Assembled ${site} — ${files.length} files, no symlinks.`);
