-- M2.3 close-out (#3): the Fix Queue's "generate a fix" step was API-only,
-- because the two things a generator needs beyond the stored Finding lived
-- nowhere durable. This migration persists both, so the dashboard can propose
-- a fix (content rewrite, GitHub PR, …) for any finding without re-crawling.

-- The page context a generator reads to build a before -> after diff: the
-- crawler had it in hand at /audit time, but /audit stored only findings and
-- threw the pages away, so nothing could rebuild `ActionContext` afterwards
-- (title for a meta fix, body for a content rewrite, entity facts come from
-- `entities`). One row per crawled URL per project; a re-crawl upserts.
create table crawled_pages (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  -- The entity this URL resolves to (§5 linkage) — the join to entity facts a
  -- schema/entity-coverage fix needs. Nullable: a crawled URL that hasn't been
  -- resolved to an entity still has title/body worth storing.
  entity_id uuid references entities(id) on delete set null,
  url text not null,
  title text,
  meta_description text,
  body_text text,
  body_html text,
  internal_link_count integer,
  updated_at timestamptz not null default now(),
  unique (project_id, url)
);

create index crawled_pages_project_id_idx on crawled_pages(project_id);

-- Where an approved fix for this project deploys, chosen once and reused for
-- every generated Action — the piece `ActionContext.target` (required) had no
-- durable home, so a fix could only be generated by a caller that passed a
-- target inline. A DeployTarget JSON object (packages/core/src/contract.ts),
-- null until the project configures one.
alter table projects add column deploy_target jsonb;
