/** A tiny real HTTP server used only by tests, so crawlPage/crawlSite get real
 * network responses (status/headers/redirects) instead of Playwright's
 * network-less `page.setContent`. Not shipped — never imported by src code. */
import { createServer, type Server } from 'node:http';
import type { AddressInfo } from 'node:net';

export interface TestServer {
  origin: string;
  /**
   * The same server reached under a different host. `localhost` and
   * `127.0.0.1` are one server and two origins, which is what a real site's
   * apex-to-`www` redirect looks like to a crawler.
   */
  altOrigin: string;
  close: () => Promise<void>;
}

const ROBOTS_TXT = `
User-agent: *
Disallow: /forbidden

User-agent: GPTBot
Disallow: /

User-agent: ClaudeBot
Allow: /

Sitemap: /sitemap.xml
`.trim();

function sitemapXml(origin: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>${origin}/</loc></url>
  <url><loc>${origin}/target</loc></url>
</urlset>`;
}

const PAGES: Record<string, (origin: string) => { status: number; headers?: Record<string, string>; body?: string }> = {
  '/': () => ({
    status: 200,
    body: `<!doctype html><html><head>
      <title>Home — Test Site</title>
      <meta name="description" content="A test page for the crawler." />
      <link rel="canonical" href="ORIGIN/" />
      <script type="application/ld+json">${JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'Organization',
        name: 'Test Co',
        url: 'ORIGIN/',
      })}</script>
    </head><body><h1>Hello</h1><a href="/target">target</a><a href="/forbidden">forbidden</a>
    <a href="mailto:hi@example.com">mail us</a></body></html>`,
  }),
  '/target': () => ({
    status: 200,
    body: `<!doctype html><html><head><title>Target</title>
      <meta name="description" content="Target page." />
      <link rel="canonical" href="ORIGIN/target" />
    </head><body>Target page</body></html>`,
  }),
  '/redirect': () => ({ status: 302, headers: { location: 'ORIGIN/target' } }),
  // Stands in for tartanhq.com's apex-to-www 301: the host that answers is not
  // the host that was asked for, and the links on the page it serves are
  // written against the host that answered.
  '/moved': () => ({ status: 301, headers: { location: 'ALT_ORIGIN/' } }),
  // A page whose HTML carries no text and no links until a script runs, which
  // is what every Framer/React site looks like at `load`.
  '/client-rendered': () => ({
    status: 200,
    body: `<!doctype html><html><head><title>Client rendered</title>
      <meta name="description" content="Rendered by script." />
    </head><body><div id="root"></div><script>
      setTimeout(function () {
        document.getElementById('root').innerHTML =
          '<main><h1>Rendered heading</h1><p>Content that only exists after hydration.</p>' +
          '<a href="/target">target</a></main>';
      }, 300);
    </script></body></html>`,
  }),
  '/noindex': () => ({
    status: 200,
    body: `<!doctype html><html><head><title>Noindex</title>
      <meta name="robots" content="noindex" />
    </head><body>Noindex page</body></html>`,
  }),
  '/broken-schema': () => ({
    status: 200,
    body: `<!doctype html><html><head><title>Broken</title>
      <meta name="description" content="Broken schema page." />
      <script type="application/ld+json">{ not valid json </script>
    </head><body>Broken</body></html>`,
  }),
  '/forbidden': () => ({ status: 200, body: '<!doctype html><title>Forbidden</title>' }),
  // A WAF block page, shaped like the one CloudFront served for tartanhq.com's
  // apex on 2026-09-10. Deliberately given a title, a heading and prose: the
  // danger is not that an error page is empty, it is that it looks like
  // content and scores like bad content.
  '/blocked': () => ({
    status: 403,
    body: `<!doctype html><html><head><title>ERROR: The request could not be satisfied</title>
    </head><body><h1>403 ERROR</h1><h2>The request could not be satisfied.</h2>
    <p>Request blocked. We can't connect to the server for this app or website at this time.</p>
    <p>Generated by cloudfront (CloudFront)</p></body></html>`,
  }),
  // Links to a path the server does not serve, so discovery queues a URL that
  // answers 404. A site's own broken link is a finding about the site, not a
  // reason to abandon the crawl.
  '/has-broken-link': () => ({
    status: 200,
    body: `<!doctype html><html><head><title>Has a broken link</title>
      <meta name="description" content="Links to a page that is gone." />
    </head><body><h1>Index</h1><a href="/gone">gone</a></body></html>`,
  }),
};

export function startTestServer(): Promise<TestServer> {
  return new Promise((resolve) => {
    const server: Server = createServer((req, res) => {
      const url = new URL(req.url ?? '/', 'http://localhost');
      if (url.pathname === '/robots.txt') {
        res.writeHead(200, { 'content-type': 'text/plain' }).end(ROBOTS_TXT);
        return;
      }
      const { port } = server.address() as AddressInfo;
      const origin = `http://localhost:${port}`;
      const altOrigin = `http://127.0.0.1:${port}`;
      if (url.pathname === '/sitemap.xml') {
        res.writeHead(200, { 'content-type': 'application/xml' }).end(sitemapXml(origin));
        return;
      }
      const handler = PAGES[url.pathname];
      if (!handler) {
        res.writeHead(404).end('not found');
        return;
      }
      const { status, headers = {}, body } = handler(origin);
      const fill = (v: string) => v.replaceAll('ALT_ORIGIN', altOrigin).replaceAll('ORIGIN', origin);
      const resolvedHeaders = Object.fromEntries(Object.entries(headers).map(([k, v]) => [k, fill(v)]));
      if (body !== undefined) resolvedHeaders['content-type'] = 'text/html; charset=utf-8';
      res.writeHead(status, resolvedHeaders);
      res.end(body === undefined ? '' : fill(body));
    });
    server.listen(0, () => {
      const { port } = server.address() as AddressInfo;
      resolve({
        origin: `http://localhost:${port}`,
        altOrigin: `http://127.0.0.1:${port}`,
        close: () => new Promise((res) => server.close(() => res())),
      });
    });
  });
}
