/**
 * M2.5 "branded reports shipping" — a self-contained branded HTML document,
 * not a dashboard panel. Pure string templating: this repo carries no
 * templating dependency (validate.ts's header already documents that
 * austerity for schema validation; the same reasoning applies here — one
 * report shape, a few dozen lines of template literal earns its keep more
 * than a rendering library would). Returned as `text/html` rather than a
 * generated PDF: Cloudflare Workers have no headless-Chromium runtime to
 * render one, and a browser's own Print-to-PDF already covers that need.
 */
import type { Account } from '@engine/core';

export interface ProjectReportRow {
  id: string;
  name: string;
  domain: string;
  healthScore: number | null;
  unifiedScore: number | null;
  keywordsTracked: number;
  citationSamples: number;
}

function esc(value: string): string {
  return value.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
}

function scoreCell(score: number | null): string {
  return score === null ? '<span class="na">not measured yet</span>' : `${Math.round(score)}`;
}

export function renderAccountReportHtml(account: Account, projects: ProjectReportRow[]): string {
  const brandColor = account.branding.primaryColor ?? '#4f46e5';
  const companyName = account.branding.companyName ?? account.name;
  const logo = account.branding.logoUrl
    ? `<img src="${esc(account.branding.logoUrl)}" alt="${esc(companyName)}" class="logo" />`
    : `<div class="logo-fallback" style="background:${esc(brandColor)}">${esc(companyName.slice(0, 1).toUpperCase())}</div>`;

  const rows = projects
    .map(
      (p) => `
        <tr>
          <td>${esc(p.name)}</td>
          <td>${esc(p.domain)}</td>
          <td>${scoreCell(p.unifiedScore)}</td>
          <td>${scoreCell(p.healthScore)}</td>
          <td>${p.keywordsTracked}</td>
          <td>${p.citationSamples}</td>
        </tr>`,
    )
    .join('');

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${esc(companyName)} — Visibility Report</title>
<style>
  :root { --brand: ${esc(brandColor)}; }
  body { font-family: system-ui, -apple-system, sans-serif; margin: 0; padding: 40px; color: #1a1a1a; background: #fff; }
  header { display: flex; align-items: center; gap: 16px; border-bottom: 3px solid var(--brand); padding-bottom: 20px; margin-bottom: 32px; }
  .logo { height: 48px; max-width: 200px; object-fit: contain; }
  .logo-fallback { height: 48px; width: 48px; border-radius: 8px; color: #fff; display: flex; align-items: center; justify-content: center; font-size: 24px; font-weight: 700; }
  h1 { font-size: 20px; margin: 0; }
  .sub { color: #666; font-size: 13px; margin-top: 2px; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #e5e5e5; font-size: 14px; }
  th { color: #666; font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: 0.03em; }
  .na { color: #999; font-style: italic; }
  footer { margin-top: 32px; color: #999; font-size: 12px; }
</style>
</head>
<body>
  <header>
    ${logo}
    <div>
      <h1>${esc(companyName)} — AI Visibility Report</h1>
      <div class="sub">${projects.length} client${projects.length === 1 ? '' : 's'} · generated ${new Date().toISOString().slice(0, 10)}</div>
    </div>
  </header>
  <table>
    <thead>
      <tr><th>Client</th><th>Domain</th><th>Unified score</th><th>Technical health</th><th>Keywords tracked</th><th>Citation samples</th></tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <footer>Generated by Engine.</footer>
</body>
</html>`;
}
